/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencv4androidexample_ImageProc */

#ifndef _Included_com_example_opencv4androidexample_ImageProc
#define _Included_com_example_opencv4androidexample_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencv4androidexample_ImageProc
 * Method:    CartoonProc
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_example_opencv4androidexample_ImageProc_CartoonProc
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_opencv4androidexample_ImageProc
 * Method:    CartoonProcNew
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_opencv4androidexample_ImageProc_CartoonProcNew
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
